<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32942" started-at="2020-10-05T09:07:37Z" finished-at="2020-10-05T09:08:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32942" started-at="2020-10-05T09:07:37Z" finished-at="2020-10-05T09:08:10Z">
      <class name="Learning.AppiumTraining.SignUpValidation_Test">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:Learning.AppiumTraining.SignUpValidation_Test@17f6480]" name="beforeClass" is-config="true" duration-ms="18773" started-at="2020-10-05T14:37:37Z" finished-at="2020-10-05T14:37:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="navigateToSignUp()[pri:0, instance:Learning.AppiumTraining.SignUpValidation_Test@17f6480]" name="navigateToSignUp" duration-ms="14146" started-at="2020-10-05T14:37:56Z" finished-at="2020-10-05T14:38:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToSignUp -->
        <test-method status="SKIP" signature="EnterDetails(java.util.ArrayList)[pri:0, instance:Learning.AppiumTraining.SignUpValidation_Test@17f6480]" name="EnterDetails" duration-ms="0" started-at="2020-10-05T14:38:10Z" data-provider="ExcelData" depends-on-methods="Learning.AppiumTraining.SignUpValidation_Test.navigateToSignUp" finished-at="2020-10-05T14:38:10Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Data Provider public java.util.ArrayList Learning.AppiumTraining.SignUpValidation_Test.ExcelData() throws java.io.IOException must return either Object[][] or Iterator<Object>[], not class java.util.ArrayList]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Data Provider public java.util.ArrayList Learning.AppiumTraining.SignUpValidation_Test.ExcelData() throws java.io.IOException must return either Object[][] or Iterator<Object>[], not class java.util.ArrayList
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
	at org.testng.internal.Invoker.createParameters(Invoker.java:991)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1081)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EnterDetails -->
      </class> <!-- Learning.AppiumTraining.SignUpValidation_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
