<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8DVPEKL" name="Learning.AppiumTraining.SignUpValidation_Test" tests="2" failures="0" timestamp="5 Oct 2020 09:08:11 GMT" time="14.146" errors="1">
  <testcase name="navigateToSignUp" time="14.146" classname="Learning.AppiumTraining.SignUpValidation_Test"/>
  <testcase name="EnterDetails" time="0.000" classname="Learning.AppiumTraining.SignUpValidation_Test">
    <error type="org.testng.TestNGException" message="
Data Provider public java.util.ArrayList Learning.AppiumTraining.SignUpValidation_Test.ExcelData() throws java.io.IOException must return either Object[][] or Iterator&lt;Object&gt;[], not class java.util.ArrayList">
      <![CDATA[org.testng.TestNGException: 
Data Provider public java.util.ArrayList Learning.AppiumTraining.SignUpValidation_Test.ExcelData() throws java.io.IOException must return either Object[][] or Iterator<Object>[], not class java.util.ArrayList
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
	at org.testng.internal.Invoker.createParameters(Invoker.java:991)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1081)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- EnterDetails -->
</testsuite> <!-- Learning.AppiumTraining.SignUpValidation_Test -->
